# Generated by Django 4.1 on 2022-09-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebook', '0003_review_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='console',
            field=models.CharField(choices=[('xbox one', 'Xbox One'), ('xbox series x', 'Xbox Series X'), ('xbox series s', 'Xbox Series s'), ('ps4', 'PS4'), ('ps5', 'PS5'), ('nintendo switch', 'Nintendo Switch'), ('pc', 'PC')], default='Choose Console', max_length=100),
        ),
    ]
